### ISSUE TITLE
The docker container is missing mne-bids and some of mne dependencies

### ISSUE THREAD

**Issue by yanbin-niu** [NDCLab/baseEEG#10] opened 2021-03-29 22:40 UTC
I got an import error while working in the container. 
<img width="819" alt="image" src="https://user-images.githubusercontent.com/79607547/112908192-aac64180-9121-11eb-94da-939a226abff5.png">

Our dockerfile uses requirements.txt to pip install all the packages and set up the environment. Other than mne-bids, nibabel and pybv, it seems requirements.txt does not include many mne dependency packages, comparing with MNE-Python environment file (https://raw.githubusercontent.com/mne-tools/mne-python/main/environment.yml), see below.

- matplotlib
- numba
- xlrd
- scikit-learn
- pillow
- statsmodels
- joblib
- psutil
- numexpr
- tqdm
- spyder-kernels>=1.10.0
- imageio-ffmpeg>=0.4.1
- vtk>=9.0.1
- pyvista>=0.24
- pyvistaqt>=0.2.0
- mayavi
- PySurfer
- dipy
- nilearn
- python-picard
- pyqt!=5.15.3
- mffpy>=0.5.7
- mne-bids
- nibabel
- pybv

**Comment by Jonhas** [comment] 2021-03-30 03:07
Thank you for bringing this up @yanbin-niu ! I've noticed the missing packages such as pybv,mne-bids, and matplotlib, but besides those packages, I haven't gotten any other import errors. There has been some issues among everyone regarding the docker container, do you think this can be resolved from installing these dependencies? We should include these within the requirements.txt file to assure everyone has the same working environment.

**Comment by yanbin-niu** [comment] 2021-03-30 05:29
@Jonhas I agree that we should include all the missing packages. We may need those packages as moving forward. Along with fixing #9 , I think we should be good, at least from what I can see.

**Comment by DMRoberts** [comment] 2021-03-30 14:21
I believe that for the most basic MNE functionality, the package mne is all that is needed, along with the dependencies like numpy, etc. that should be automatically installed by pip when installing mne. The issue is that once you move beyond that most basic functionality, additional packages are needed. So in our case, exporting to BIDS required mne-bids and pybv, etc.

We may not end up needing all of these additional packages that MNE lists in their Conda environment, though it might be best just to configure our Docker container to include them all in advance, to minimize the frequency at which we update the Docker container at a later time. I think for our Docker container, we'll just want to specify the version number for each, to be sure that the Docker image is consistent. I believe in the Conda environment file that MNE has provided, most of the packages (those without version number indicated) will install the latest compatible version at the time the environment is created, which will change over time.

For mne-bids and pybv, I had added them to requirements.txt in my local branch, and submitted a pull request.

**Comment by georgebuzzell** [comment] 2021-03-31 11:56
@yanbin-niu I merged @DMRoberts pull request adding in mne-bids and pybv. 

Dan's pull request was to dev-feature-io. Can you please create a new branch off of dev-feature-io to dev-feature-io-yanbin, push your commits for updating the docker file to dev-feature-io-yanbin, then do a pull request to dev-feature-io? I will review and accept the pull request. I will then do a pull request from dev-feature-io to dev. That way, both dev, and dev-feature-io will have the updated docker file, which will then include both the edits of @DMRoberts and your edits, @yanbin-niu

**Comment by yanbin-niu** [comment] 2021-03-31 13:26
@DMRoberts Thanks for your comments! I do not think the MNE package will automatically install other dependencies. If you import matplotlib in the container, it will throw out an error. I do agree your concerns about updating the packages. I think we do not have to specify versions , just like what did by the MNE environment file, and the docker will download the latest versions. The only work from us is, we may need to rebuild a new image sometimes. Does it make sense ? @georgebuzzell how do you think about this?

**Comment by georgebuzzell** [comment] 2021-03-31 13:38
@yanbin-niu Thank you for thinking about this. I think there MIGHT be a miscommunication here, but maybe it is on my end. :)

Basically, I don't think @DMRoberts was saying that the MNE Package will automatically install the other dependencies. We actually all agree on that. I think @DMRoberts was just saying that he didnt think those other dependencies were neccesary yet, BUT, they likely will be in the future. So, I would say that we do want to update the docker file to list ALL of the dependencies that the conda file would normally download automatically. 

However, the place where it sounds like there is confusion, is that I do agree with @DMRoberts that we want to specify the exact versions in our docker file. I know that the conda approach does not do that, and just downloads the most recent, but that is problematic as it then means that depending on when someone builds their docker file they might have slightly different versions of the dependencies. That is counter to the reason we are using docker, which is to ensure that we all have the EXACT SAME environment. As @DMRoberts suggested, the way to do that, is to specify the exact version number for ALL dependencies. Does that make sense? @yanbin-niu do you agree with this or do you see an issue here that maybe @DMRoberts or I might be missing? Please, do not hesitate to say so if you do! :)

**Comment by yanbin-niu** [comment] 2021-03-31 13:53
@georgebuzzell I do agree you said about "it then means that depending on when someone builds their docker file they might have slightly different versions of the dependencies." However, this is what mne does. Like what @DMRoberts was concerned about, if we specify the version for all the dependencies, we may need to check every so often what the latest version they are using and update our requirement.txt correspondingly. Does this make sense?

**Comment by georgebuzzell** [comment] 2021-03-31 13:59
@yanbin-niu Yes, makes perfect sense! So we agree the way forward is to specify the versions explicitly, and then, every so often we check for the latest versions and update our docker file, and make sure everyone switches over to the updated docker file. Yes?

**Comment by yanbin-niu** [comment] 2021-03-31 14:09
@georgebuzzell Sounds good to me now! Sorry for the misunderstanding !

**Comment by georgebuzzell** [comment] 2021-03-31 14:10
@yanbin-niu Please, NO APOLOGIES needed!! Thank you for working on this. And thank you for QUESTIONING things; that is always a good thing! :)

**Closed** 2021-04-02 12:18 UTC
